name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Backend: Install dependencies
      - name: Install backend dependencies
        working-directory: ./api
        run: npm install

      # 4️⃣ Backend: Lint
      - name: Lint backend
        working-directory: ./api
        run: npm run lint || true  # optional: fail on lint errors if you want

      # 5️⃣ Frontend: Install dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # 6️⃣ Frontend: Lint
      - name: Lint frontend
        working-directory: ./frontend
        run: npm run lint || true  # optional

      # 7️⃣ Frontend: Build
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
